### ISSUE TITLE
Set python environment with casatools installed

### ISSUE THREAD

**Issue by rohitcbscient** [PredragMatavulj/STIX-MWA#2]
We can create a standard Python environment and the package for MWA data analysis.
First, we would need to install casatools.

**Comment by PredragMatavulj** [comment]
Python environment created, there are requirements.txt for installation with pip, or environment.yaml for conda environment setup. The latest version of CASA, version 6.6, requires Python versions 3.8 or 3.10. Then it could be installed with pip. More in the readme file.
